spring.application.name=activityservice

# MongoDB configuration
#spring.data.mongodb.uri=mongodb://localhost:27017/activity_db

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=activity_db
logging.level.org.springframework.data.mongodb=DEBUG

server.port=8082

